# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('methode', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('especes', 'Espèces')], max_length=20)),
                ('moment', models.CharField(choices=[('en_ligne', 'En ligne'), ('a_la_livraison', 'À la livraison')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference_prestataire', models.CharField(blank=True, max_length=100, null=True)),
                ('paye_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='users.client')),
            ],
            options={
                'db_table': 'paiements',
            },
        ),
    ]
