# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='colis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='paiements', to='shipments.colis'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['colis'], name='paiements_colis_i_93936e_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['client'], name='paiements_client__a91eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut'], name='paiements_statut_ce5cce_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.CheckConstraint(condition=models.Q(('methode', 'especes'), ('moment', 'en_ligne'), _negated=True), name='chk_paiement_coherent'),
        ),
    ]
