# Generated by Django 6.0.7 on 2026-08-11 09:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('desactive', 'Désactivé')], default='actif', max_length=10)),
                ('telephone_verifie_le', models.DateTimeField(blank=True, null=True)),
                ('jeton_connexion', models.CharField(blank=True, max_length=100, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='administrateur', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrateurs',
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code_client', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'clients',
            },
            bases=('users.utilisateur',),
        ),
        migrations.CreateModel(
            name='CodeOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=10)),
                ('expire_le', models.DateTimeField()),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codes_otp',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(db_column='id_utilisateur', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('localisation', models.CharField(choices=[('chine', 'Chine'), ('cameroun', 'Cameroun')], default='chine', max_length=20)),
                ('supprime_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='agents_crees', to='users.administrateur')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='agents_supprimes', to='users.administrateur')),
            ],
            options={
                'db_table': 'agents',
            },
            bases=('users.utilisateur',),
        ),
    ]
