# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotDedouanement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_besc', models.CharField(max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_dedouanement', to='users.administrateur')),
            ],
            options={
                'db_table': 'lots_dedouanement',
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_suivi', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('mode_transport', models.CharField(choices=[('aerien_express', 'Aérien express'), ('aerien_standard', 'Aérien standard'), ('maritime', 'Maritime')], max_length=20)),
                ('photo_declaree_url', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('declaree', 'Déclarée'), ('recu_entrepot', "Reçu à l'entrepôt"), ('embarque', 'Embarqué'), ('en_transit', 'En transit'), ('dedouanement', 'Dédouanement'), ('arrive_depot_local', 'Arrivé au dépôt local'), ('en_livraison', 'En livraison'), ('livre', 'Livré')], default='declaree', max_length=20)),
                ('cout_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cout_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_livraison_estimee', models.DateField(blank=True, null=True)),
                ('numero_besc', models.CharField(blank=True, max_length=50, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='colis', to='users.client')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='shipments.lotdedouanement')),
            ],
            options={
                'db_table': 'colis',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_transport', models.CharField(choices=[('aerien_express', 'Aérien express'), ('aerien_standard', 'Aérien standard'), ('maritime', 'Maritime')], max_length=20)),
                ('prix_par_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_par_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delai_estime_jours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('administrateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifs', to='users.administrateur')),
            ],
            options={
                'db_table': 'tarifs',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('retard', 'Retard'), ('blocage_douane', 'Blocage douane'), ('avarie', 'Avarie'), ('perte_partielle', 'Perte partielle'), ('autre', 'Autre')], max_length=20)),
                ('gravite', models.CharField(choices=[('information', 'Information'), ('important', 'Important'), ('critique', 'Critique')], default='information', max_length=20)),
                ('description', models.TextField()),
                ('resolu_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('colis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='shipments.colis')),
                ('declare_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_declares', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='shipments.lotdedouanement')),
            ],
            options={
                'db_table': 'incidents',
                'indexes': [models.Index(fields=['colis'], name='incidents_colis_i_734ef5_idx'), models.Index(fields=['lot'], name='incidents_lot_id_018650_idx'), models.Index(fields=['resolu_le'], name='incidents_resolu__53fd5b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('colis__isnull', False), ('lot__isnull', True)), models.Q(('colis__isnull', True), ('lot__isnull', False)), _connector='OR'), name='chk_incident_cible')],
            },
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['client'], name='colis_client__738002_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['statut'], name='colis_statut_355976_idx'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['statut', 'date_livraison_estimee'], name='colis_statut_840024_idx'),
        ),
    ]
