# Generated by Django 6.0.8 on 2026-08-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_colis_cout_estime_alter_colis_cout_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colis',
            options={'ordering': ['-cree_le']},
        ),
    ]
