# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_reclamation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages_reclamation',
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('colis_endommage', 'Colis endommagé'), ('retard', 'Retard'), ('disparu', 'Disparu'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('resolue', 'Résolue'), ('rejetee', 'Rejetée')], default='ouverte', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('agent_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reclamations', to='users.client')),
            ],
            options={
                'db_table': 'reclamations',
            },
        ),
    ]
