# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='colis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='shipments.colis'),
        ),
        migrations.AddField(
            model_name='messagereclamation',
            name='reclamation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.reclamation'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['colis'], name='reclamation_colis_i_1636a2_idx'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['statut'], name='reclamation_statut_7d6ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereclamation',
            index=models.Index(fields=['reclamation', 'cree_le'], name='messages_re_reclama_8a6e42_idx'),
        ),
    ]
