# Generated by Django 6.0.7 on 2026-08-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStatutColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('declaree', 'Déclarée'), ('recu_entrepot', "Reçu à l'entrepôt"), ('embarque', 'Embarqué'), ('en_transit', 'En transit'), ('dedouanement', 'Dédouanement'), ('arrive_depot_local', 'Arrivé au dépôt local'), ('en_livraison', 'En livraison'), ('livre', 'Livré')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='changements_statuts_colis', to='users.agent')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='shipments.colis')),
            ],
            options={
                'db_table': 'historique_statut_colis',
            },
        ),
        migrations.CreateModel(
            name='PhotoColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], default='photo', max_length=10)),
                ('url', models.CharField(max_length=255)),
                ('prise_le', models.DateTimeField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='photos_prises', to='users.agent')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shipments.colis')),
                ('historique_statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='tracking.historiquestatutcolis')),
            ],
            options={
                'db_table': 'photos_colis',
            },
        ),
        migrations.AddIndex(
            model_name='historiquestatutcolis',
            index=models.Index(fields=['colis', 'cree_le'], name='historique__colis_i_779b74_idx'),
        ),
        migrations.AddIndex(
            model_name='photocolis',
            index=models.Index(fields=['colis'], name='photos_coli_colis_i_b31c5d_idx'),
        ),
    ]
