# Generated by Django 6.0.8 on 2026-08-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocolis',
            name='url',
            field=models.ImageField(upload_to='colis_photos/%Y/%m/'),
        ),
    ]
