# Generated by Django 6.0.7 on 2026-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('statut_colis', 'Statut du colis'), ('paiement', 'Paiement'), ('reclamation', 'Réclamation'), ('incident', 'Incident'), ('general', 'Général')], max_length=20)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push'), ('email', 'Email')], max_length=10)),
                ('contenu', models.CharField(max_length=255)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('lu_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
